const HSK3_VOCAB = [
  {w:'爱心',p:'名',m:'love, kind heart',e:'她很有爱心，经常帮助流浪小动物。',l:3},
  {w:'安排',p:'动、名',m:'arrange; arrangement',e:'老师安排我们下周去参观长城。',l:3},
  {w:'安装',p:'动',m:'install',e:'师傅来家里安装新洗衣机。',l:3},
  {w:'按',p:'动、介',m:'press; according to',e:'按红色按钮机器就能启动。',l:3},
  {w:'按照',p:'介',m:'according to',e:'按照学校规定，上课不能玩手机。',l:3},
  {w:'把¹',p:'介',m:'object particle',e:'把课本放到桌子上面。',l:3},
  {w:'把²',p:'量',m:'bundle, handful',e:'一把尺子、一把椅子。',l:3},
  {w:'把握',p:'动、名',m:'grasp; seize',e:'我们要把握住这次汉语比赛的机会。',l:3},
  {w:'白',p:'副',m:'white; bright',e:'这件白色上衣很好看。',l:3},
  {w:'白菜',p:'名',m:'Chinese cabbage',e:'晚饭我吃米饭和白菜。',l:3},
  {w:'班级',p:'名',m:'class',e:'我们班级一共有 28 名学生。',l:3},
  {w:'搬',p:'动',m:'carry, move',e:'下周我搬去新公寓住。',l:3},
  {w:'搬家',p:'动',m:'move house',e:'下个月我打算搬家。',l:3},
  {w:'板',p:'名',m:'board, plank',e:'黑板上写着很多汉字。',l:3},
  {w:'办理',p:'动',m:'handle, go through',e:'去大厅办理入住手续。',l:3},
  {w:'保',p:'动',m:'keep, protect',e:'保护好你的身份证，不要弄丢。',l:3},
  {w:'保安',p:'名',m:'security guard',e:'学校门口的保安很热心。',l:3},
  {w:'保持',p:'动',m:'maintain, keep',e:'每天保持朗读半小时汉语。',l:3},
  {w:'保存',p:'动',m:'save, store',e:'保存好这份重要考试资料。',l:3},
  {w:'保护',p:'动',m:'protect',e:'我们要保护大自然。',l:3},
  {w:'保留',p:'动',m:'reserve, keep',e:'这个传统我们要一直保留下去。',l:3},
  {w:'保险',p:'形、名',m:'safe; insurance',e:'买一份人身保险更安心。',l:3},
  {w:'保证',p:'动、名',m:'guarantee; promise',e:'我保证明天一定不迟到。',l:3},
  {w:'报',p:'动、名',m:'report; newspaper',e:'今天的报纸已经送到了。',l:3},
  {w:'报到',p:'动',m:'register, check in',e:'新生明天早上八点来教室报到。',l:3},
  {w:'报道',p:'动、名',m:'report news',e:'记者报道了这次比赛的情况。',l:3},
  {w:'报告',p:'动、名',m:'report; speech',e:'学生向老师报告作业完成情况。',l:3},
  {w:'背',p:'动',m:'carry on back',e:'我背书包去学校。',l:3},
  {w:'北部',p:'名',m:'north part',e:'中国北部冬天很冷。',l:3},
  {w:'背',p:'名',m:'back',e:'我的背后有一个书包。',l:3},
  {w:'背后',p:'名',m:'back, behind',e:'有人站在我的背后。',l:3},
  {w:'被',p:'介',m:'passive particle',e:'杯子被我不小心打碎了。',l:3},
  {w:'被子',p:'名',m:'quilt, blanket',e:'冬天盖厚被子很暖和。',l:3},
  {w:'本来',p:'形、副',m:'original; originally',e:'我本来打算昨天去逛街。',l:3},
  {w:'本领',p:'名',m:'skill, ability',e:'他做饭的本领特别高。',l:3},
  {w:'本事',p:'名',m:'skill, capability',e:'修理电器是他的本事。',l:3},
  {w:'比较',p:'副、动',m:'quite; compare',e:'这件衣服比较便宜。',l:3},
  {w:'比例',p:'名',m:'proportion, ratio',e:'男女学生的比例差不多一样。',l:3},
  {w:'比赛',p:'动、名',m:'compete; match',e:'我们明天要进行篮球比赛。',l:3},
  {w:'必然',p:'形',m:'inevitable',e:'努力学习，进步是必然的。',l:3},
  {w:'必要',p:'形、名',m:'necessary; necessity',e:'带词典是学习汉语的必要准备。',l:3},
  {w:'变化',p:'动、名',m:'change; variation',e:'天气的变化很大。',l:3},
  {w:'变为',p:'动',m:'become, turn into',e:'小树慢慢变为大树。',l:3},
  {w:'标题',p:'名',m:'title',e:'这篇文章的标题很简单。',l:3},
  {w:'标准',p:'名、形',m:'standard; standardised',e:'这是考试的评分标准。',l:3},
  {w:'表达',p:'动',m:'express',e:'用汉语表达自己的想法。',l:3},
  {w:'表格',p:'名',m:'form, table',e:'填写这张报名表格。',l:3},
  {w:'表面',p:'名',m:'surface',e:'桌子表面非常干净。',l:3},
  {w:'表明',p:'动',m:'show, indicate',e:'这件事表明他很认真。',l:3},
  {w:'表现',p:'动、名',m:'perform; performance',e:'他课堂上的表现很好。',l:3},
  {w:'表演',p:'动、名',m:'perform; show',e:'小朋友上台表演节目。',l:3},
  {w:'并',p:'副、连',m:'also; and',e:'大家都同意并支持老板的决定。',l:3},
  {w:'并且',p:'连',m:'and, besides',e:'他会唱歌，并且会跳舞。',l:3},
  {w:'播出',p:'动',m:'broadcast',e:'电视台每天播出新闻。',l:3},
  {w:'播放',p:'动',m:'play, broadcast',e:'播放中文歌曲练习听力。',l:3},
  {w:'不必',p:'副',m:'need not',e:'不必每天很早来教室。',l:3},
  {w:'不断',p:'动、副',m:'continue; constantly',e:'不断练习才能学好汉语。',l:3},
  {w:'不论',p:'连',m:'no matter',e:'不论天气好坏，他都按时上课。',l:3},
  {w:'补',p:'动',m:'make up, add',e:'补一下昨天没写完的作业。',l:3},
  {w:'补充',p:'动、名',m:'supplement; addition',e:'老师补充了几个生词。',l:3},
  {w:'不安',p:'形',m:'uneasy, worried',e:'没复习，我心里很不安。',l:3},
  {w:'不得不',p:'副',m:'have to',e:'下雨了，我不得不打车回家。',l:3},
  {w:'不光',p:'副、连',m:'not only',e:'不光我，所有人都喜欢这部剧。',l:3},
  {w:'不仅',p:'连',m:'not only',e:'他不仅会说汉语，还会写汉字。',l:3},
  {w:'布',p:'名',m:'cloth',e:'这块布可以做衣服。',l:3},
  {w:'步',p:'名、量',m:'step; pace',e:'一步一步慢慢走。',l:3},
  {w:'部',p:'名、量',m:'department; volume',e:'一部好看的电视剧。',l:3},
  {w:'部门',p:'名',m:'department',e:'学校的行政部门在一楼。',l:3},
  {w:'部长',p:'名',m:'minister, department head',e:'这位部长负责文化工作。',l:3},
  {w:'才能',p:'名',m:'talent, ability',e:'每个人都有自己的才能。',l:3},
  {w:'采取',p:'动',m:'adopt, take',e:'采取简单的学习方法。',l:3},
  {w:'采用',p:'动',m:'adopt, use',e:'学校采用新的教学方法。',l:3},
  {w:'彩色',p:'名',m:'color, colorful',e:'彩色图画很好看。',l:3},
  {w:'曾经',p:'副',m:'once, used to',e:'我曾经在北京生活两年。',l:3},
  {w:'产生',p:'动',m:'produce, generate',e:'努力会产生好的结果。',l:3},
  {w:'长城',p:'名',m:'the Great Wall',e:'长城是中国的著名景点。',l:3},
  {w:'长处',p:'名',m:'strong point, advantage',e:'耐心是他的长处。',l:3},
  {w:'长期',p:'名',m:'long term',e:'长期坚持练习汉语。',l:3},
  {w:'厂',p:'名',m:'factory',e:'这家工厂生产家具。',l:3},
  {w:'场合',p:'名',m:'occasion',e:'正式场合要注意说话方式。',l:3},
  {w:'场所',p:'名',m:'place, venue',e:'公园是休闲的场所。',l:3},
  {w:'超级',p:'形',m:'super, extremely',e:'这家超市超级大。',l:3},
  {w:'朝',p:'介、动',m:'towards; face',e:'他朝教室的方向走去。',l:3},
  {w:'吵',p:'形、动',m:'noisy; quarrel',e:'不要在房间里吵。',l:3},
  {w:'吵架',p:'动',m:'quarrel',e:'好朋友不要轻易吵架。',l:3},
  {w:'衬衫',p:'名',m:'shirt',e:'这件蓝色衬衫很合身。',l:3},
  {w:'衬衣',p:'名',m:'shirt',e:'夏天穿薄衬衣很舒服。',l:3},
  {w:'称为',p:'动',m:'be called',e:'这座山被称为青山。',l:3},
  {w:'成功',p:'动、形',m:'succeed; successful',e:'这次考试我成功通过了。',l:3},
  {w:'成果',p:'名',m:'achievement, result',e:'他工作了一年，取得了很多工作成果。',l:3},
  {w:'成就',p:'名、动',m:'achievement; accomplish',e:'他取得了很大的成就。',l:3},
  {w:'成立',p:'动',m:'establish, set up',e:'学校成立了汉语社团。',l:3},
  {w:'成熟',p:'形',m:'mature',e:'这个苹果已经成熟了。',l:3},
  {w:'成员',p:'名',m:'member',e:'社团一共有十名成员。',l:3},
  {w:'成长',p:'动',m:'grow up',e:'孩子在慢慢成长。',l:3},
  {w:'城',p:'名',m:'city',e:'这座城有很多高楼。',l:3},
  {w:'城市',p:'名',m:'city',e:'大城市交通很方便。',l:3},
  {w:'程度',p:'名',m:'degree, level',e:'成就的大小关键在于努力的程度。',l:3},
  {w:'持续',p:'动',m:'last, continue',e:'大雨持续下了一整夜。',l:3},
  {w:'充满',p:'动',m:'be full of',e:'房间里充满快乐的笑声。',l:3},
  {w:'重',p:'副',m:'again, once more',e:'重看一遍这部电影。',l:3},
  {w:'初',p:'前缀',m:'early, first',e:'初一学生学习简单的汉语。',l:3},
  {w:'初步',p:'形',m:'initial, preliminary',e:'初步了解中国文化。',l:3},
  {w:'初级',p:'形',m:'elementary, beginner',e:'初级汉语课本很简单。',l:3},
  {w:'初中',p:'名',m:'junior middle school',e:'我以前在初中学习英语。',l:3},
  {w:'除了',p:'介',m:'besides, except',e:'除了汉语，我还学画画。',l:3},
  {w:'处理',p:'动、名',m:'deal with; handle',e:'处理生活里的小事。',l:3},
  {w:'传',p:'动',m:'pass, spread',e:'把知识传给学生。',l:3},
  {w:'传播',p:'动',m:'spread, disseminate',e:'传播中国传统文化。',l:3},
  {w:'传来',p:'动',m:'come over, spread',e:'远处传来好听的歌声。',l:3},
  {w:'传说',p:'动、名',m:'legend; pass on',e:'这是一个古老的传说。',l:3},
  {w:'创新',p:'动',m:'innovate',e:'学生要学会创新思考。',l:3},
  {w:'创业',p:'动',m:'start a business',e:'年轻人可以勇敢创业。',l:3},
  {w:'创造',p:'动、名',m:'create; creation',e:'创造属于自己的作品。',l:3},
  {w:'创作',p:'动、名',m:'create work; writing',e:'作家创作新小说。',l:3},
  {w:'从来',p:'副',m:'ever, always',e:'我从来没有去过上海。',l:3},
  {w:'从前',p:'名',m:'past, former time',e:'从前这里是一片草地。',l:3},
  {w:'从事',p:'动',m:'engage in',e:'他从事汉语教学工作。',l:3},
  {w:'村',p:'名',m:'village',e:'我的家乡在一个小村。',l:3},
  {w:'存',p:'动',m:'exist, keep',e:'存好你的零花钱。',l:3},
  {w:'存在',p:'动',m:'exist',e:'很多问题依然存在。',l:3},
  {w:'错误',p:'形、名',m:'wrong; mistake',e:'这道题有一个错误。',l:3},
  {w:'达到',p:'动',m:'reach, achieve',e:'汉语水平达到三级水平。',l:3},
  {w:'打破',p:'动',m:'break, break through',e:'我打破了桌上的玻璃杯。',l:3},
  {w:'打听',p:'动',m:'ask about, inquire',e:'打听去车站的路线。',l:3},
  {w:'大概',p:'形、副',m:'rough; probably',e:'大概下午三点上课。',l:3},
  {w:'大使馆',p:'名',m:'embassy',e:'中国大使馆在这座城市中心。',l:3},
  {w:'大约',p:'副',m:'about, around',e:'大约二十个人参加活动。',l:3},
  {w:'大夫',p:'名',m:'doctor',e:'不舒服就去找大夫看一看。',l:3},
  {w:'代',p:'动、名',m:'replace; generation',e:'我们这一代喜欢学习外语。',l:3},
  {w:'代表',p:'动、名',m:'represent; representative',e:'他代表班级发言。',l:3},
  {w:'代表团',p:'名',m:'delegation',e:'代表团明天来学校参观。',l:3},
  {w:'带动',p:'动',m:'drive, promote',e:'带动大家一起学习汉语。',l:3},
  {w:'带领',p:'动',m:'lead, take',e:'老师带领我们参观博物馆。',l:3},
  {w:'单元',p:'名',m:'unit',e:'课本一共有八个单元。',l:3},
  {w:'当初',p:'名',m:'at first, originally',e:'当初我刚来中国的时候不会说汉语。',l:3},
  {w:'当地',p:'名',m:'local',e:'当地美食非常好吃。',l:3},
  {w:'当然',p:'形、副',m:'natural; of course',e:'我当然愿意帮助你。',l:3},
  {w:'当中',p:'名',m:'middle, among',e:'人群当中有我的朋友。',l:3},
  {w:'刀',p:'名',m:'knife',e:'用小刀切水果。',l:3},
  {w:'导演',p:'动、名',m:'direct; director',e:'这位导演拍了很多电视剧。',l:3},
  {w:'到达',p:'动',m:'arrive',e:'我明天早上八点到达上海。',l:3},
  {w:'到底',p:'副',m:'after all, finally',e:'你到底什么时候来？',l:3},
  {w:'得分',p:'动、名',m:'score; points',e:'比赛他得分最高。',l:3},
  {w:'等待',p:'动',m:'wait for',e:'等待朋友一起吃饭。',l:3},
  {w:'底下',p:'名',m:'below, under',e:'桌子底下有一支笔。',l:3},
  {w:'地区',p:'名',m:'area, region',e:'这个地区气候很温暖。',l:3},
  {w:'电视剧',p:'名',m:'TV drama',e:'晚上我喜欢看电视剧。',l:3},
  {w:'电视台',p:'名',m:'TV station',e:'本地电视台每天播放新闻。',l:3},
  {w:'电台',p:'名',m:'radio station',e:'电台播放中文广播。',l:3},
  {w:'电子邮件',p:'名',m:'email',e:'每天查看电子邮件。',l:3},
  {w:'调',p:'动',m:'adjust, transfer',e:'调一下空调温度。',l:3},
  {w:'调查',p:'动、名',m:'investigate; survey',e:'调查学生的学习习惯。',l:3},
  {w:'订',p:'动',m:'order, book',e:'订明天的火车票。',l:3},
  {w:'定期',p:'动、形',m:'regular; fixed',e:'定期去图书馆看书。',l:3},
  {w:'东部',p:'名',m:'east part',e:'国家东部经济很发达。',l:3},
  {w:'动力',p:'名',m:'power, motivation',e:'兴趣是学习的动力。',l:3},
  {w:'动人',p:'形',m:'moving, touching',e:'动人的故事让人感动。',l:3},
  {w:'读者',p:'名',m:'reader',e:'这本书有很多读者。',l:3},
  {w:'短处',p:'名',m:'shortcoming, weakness',e:'胆小是他的短处。',l:3},
  {w:'短裤',p:'名',m:'shorts',e:'夏天穿短裤很凉快。',l:3},
  {w:'短期',p:'名',m:'short term',e:'短期汉语班一共两个月。',l:3},
  {w:'断',p:'动',m:'break, cut off',e:'电线断了，没有电了。',l:3},
  {w:'队员',p:'名',m:'team member',e:'篮球队队员每天训练。',l:3},
  {w:'对待',p:'动',m:'treat',e:'对待同学要友好。',l:3},
  {w:'对方',p:'名',m:'the other side',e:'听清楚对方说的话。',l:3},
  {w:'对手',p:'名',m:'opponent, rival',e:'比赛对手实力很强。',l:3},
  {w:'对象',p:'名',m:'object, target',e:'这个项目的服务对象是老年人。',l:3},
  {w:'顿',p:'量',m:'time (meal)',e:'][一天三顿饭。',l:3},
  {w:'发表',p:'动',m:'publish, publish',e:'发表自己写的短文。',l:3},
  {w:'发出',p:'动',m:'send out, emit',e:'发出求救的声音。',l:3},
  {w:'发达',p:'形',m:'developed',e:'这座城市交通很发达。',l:3},
  {w:'发动',p:'动',m:'launch, start',e:'发动大家一起参加活动。',l:3},
  {w:'发明',p:'动、名',m:'invent; invention',e:'中国人发明了纸。',l:3},
  {w:'发生',p:'动',m:'happen, occur',e:'昨天这里发生了一件趣事。',l:3},
  {w:'发送',p:'动',m:'send',e:'发送电子邮件给老师。',l:3},
  {w:'发言',p:'动、名',m:'speak; speech',e:'课堂上积极发言。',l:3},
  {w:'发展',p:'动、名',m:'develop; development',e:'国家发展得越来越快。',l:3},
  {w:'反对',p:'动',m:'oppose, disagree',e:'我反对这个不好的计划。',l:3},
  {w:'反复',p:'副、名',m:'repeatedly; repeat',e:'反复朗读生词记住更快。',l:3},
  {w:'反应',p:'动、名',m:'react; response',e:'他听到消息反应很快。',l:3},
  {w:'反正',p:'副',m:'anyway, no matter',e:'不管你去不去，反正我明天一定去。',l:3},
  {w:'范围',p:'名',m:'range, scope',e:'考试范围已经发给大家。',l:3},
  {w:'方式',p:'名',m:'way, method',e:'用简单的方式学习汉语。',l:3},
  {w:'防',p:'动',m:'prevent, guard',e:'为了防下雨，我随身带伞。',l:3},
  {w:'防止',p:'动',m:'prevent',e:'防止上课迟到。',l:3},
  {w:'房东',p:'名',m:'landlord, landlady',e:'房东很好，房租不贵。',l:3},
  {w:'房屋',p:'名',m:'house, building',e:'这片房屋都是新的。',l:3},
  {w:'房租',p:'名',m:'rent',e:'每个月交一次房租。',l:3},
  {w:'访问',p:'动',m:'visit, interview',e:'美国领导人准备访问中国。',l:3},
  {w:'放到',p:'动',m:'put into',e:'把书本放到书包里。',l:3},
  {w:'飞行',p:'动',m:'fly',e:'飞机在天上飞行。',l:3},
  {w:'费',p:'名',m:'fee, cost',e:'学费一年一交。',l:3},
  {w:'费用',p:'名',m:'expense, cost',e:'生活费用不算很高。',l:3},
  {w:'分别',p:'动、副',m:'separate; respectively',e:'我们分别从不同国家来。',l:3},
  {w:'分配',p:'动',m:'distribute, assign',e:'老师分配了新的学习任务。',l:3},
  {w:'分组',p:'动',m:'divide into groups',e:'课堂上分组练习对话。',l:3},
  {w:'丰富',p:'形',m:'rich, abundant',e:'他教了20年，有丰富的教学经验。',l:3},
  {w:'风险',p:'名',m:'risk',e:'做这件事有一点风险。',l:3},
  {w:'否定',p:'动、形',m:'deny; negative',e:'不要否定别人的想法。',l:3},
  {w:'否认',p:'动',m:'deny',e:'他否认自己做错了事情。',l:3},
  {w:'服装',p:'名',m:'clothing, clothes',e:'这家店卖好看的服装。',l:3},
  {w:'福',p:'名',m:'blessing, good fortune',e:'奶奶一辈子都很有福气。',l:3},
  {w:'父母',p:'名',m:'parents',e:'我的父母都很支持我学汉语。',l:3},
  {w:'父亲',p:'名',m:'father',e:'我的父亲喜欢喝茶。',l:3},
  {w:'付',p:'动',m:'pay',e:'付饭钱给老板。',l:3},
  {w:'负责',p:'动、形',m:'be responsible for; responsible',e:'我负责打扫教室。',l:3},
  {w:'复印',p:'动',m:'copy, photocopy',e:'复印这份汉语试卷。',l:3},
  {w:'复杂',p:'形',m:'complicated',e:'这个语法有点复杂。',l:3},
  {w:'富',p:'形',m:'rich',e:'这里的人都很富。',l:3},
  {w:'改进',p:'动',m:'improve',e:'改进自己的学习方法。',l:3},
  {w:'改造',p:'动',m:'reform, rebuild',e:'改造旧的房间。',l:3},
  {w:'概念',p:'名',m:'concept, idea',e:'明白这个汉语概念很重要。',l:3},
  {w:'赶',p:'动',m:'hurry, catch',e:'赶公交车去学校。',l:3},
  {w:'赶到',p:'动',m:'arrive in time',e:'早上七点赶到教室。',l:3},
  {w:'赶紧',p:'副',m:'hurriedly, quickly',e:'赶紧写完作业出去玩。',l:3},
  {w:'赶快',p:'副',m:'at once, hurry up',e:'赶快收拾东西出门。',l:3},
  {w:'敢',p:'动',m:'dare',e:'我敢主动和中国人聊天。',l:3},
  {w:'感冒',p:'名、动',m:'cold; catch a cold',e:'天冷很容易感冒。',l:3},
  {w:'感情',p:'名',m:'feeling, emotion',e:'我们之间感情很好。',l:3},
  {w:'感受',p:'名、动',m:'feeling; feel',e:'感受中国的生活文化。',l:3},
  {w:'干吗',p:'代',m:'what for, why',e:'你周末干吗去？',l:3},
  {w:'高速',p:'形',m:'high speed',e:'高速列车速度很快。',l:3},
  {w:'高速公路',p:'名',m:'highway',e:'走高速公路回家。',l:3},
  {w:'告别',p:'动',m:'say goodbye',e:'和朋友告别。',l:3},
  {w:'歌迷',p:'名',m:'music fan',e:'他是这位歌手的歌迷。',l:3},
  {w:'歌声',p:'名',m:'singing voice',e:'她唱的歌声很好听。',l:3},
  {w:'歌手',p:'名',m:'singer',e:'这位歌手会唱中文歌。',l:3},
  {w:'个人',p:'名',m:'individual, person',e:'每个人都有自己的爱好。',l:3},
  {w:'个性',p:'名',m:'personality',e:'他的个性开朗活泼。',l:3},
  {w:'各',p:'代、副',m:'each, every',e:'各国学生一起上课。',l:3},
  {w:'各地',p:'名',m:'every place',e:'各地美食味道不一样。',l:3},
  {w:'各位',p:'代',m:'everybody, all',e:'各位同学请安静。',l:3},
  {w:'各种',p:'代',m:'all kinds of',e:'超市有各种水果。',l:3},
  {w:'各自',p:'代',m:'each respective',e:'我们各自回自己的房间。',l:3},
  {w:'根本',p:'副、形、名',m:'at all; basic; root',e:'根本没有时间出去玩。',l:3},
  {w:'更加',p:'副',m:'more, even more',e:'努力之后汉语更加流利了。',l:3},
  {w:'工厂',p:'名',m:'factory',e:'这家工厂生产手机。',l:3},
  {w:'工程师',p:'名',m:'engineer',e:'工程师设计新房子。',l:3},
  {w:'工夫',p:'名',m:'time, effort',e:'学汉语需要很多工夫。',l:3},
  {w:'工具',p:'名',m:'tool',e:'笔是学习的工具。',l:3},
  {w:'工业',p:'名',m:'industry',e:'这座城市工业很发达。',l:3},
  {w:'工资',p:'名',m:'salary, wage',e:'每个月按时发工资。',l:3},
  {w:'公布',p:'动',m:'announce, publish',e:'公布这次考试成绩。',l:3},
  {w:'公共',p:'形',m:'public',e:'公共汽车很便宜。',l:3},
  {w:'公开',p:'形、动',m:'open; make public',e:'公开分享自己的学习经验。',l:3},
  {w:'公民',p:'名',m:'citizen',e:'每个公民遵守法律。',l:3},
  {w:'公务员',p:'名',m:'civil servant',e:'他毕业后做公务员。',l:3},
  {w:'功夫',p:'名',m:'skill, kung fu',e:'他会中国功夫。',l:3},
  {w:'功课',p:'名',m:'schoolwork, homework',e:'每天完成当天功课。',l:3},
  {w:'功能',p:'名',m:'function',e:'手机有很多实用功能。',l:3},
  {w:'共同',p:'形',m:'common',e:'我们共同完成小组作业。',l:3},
  {w:'共有',p:'动',m:'share, own together',e:'这个房间共有两个人住。',l:3},
  {w:'姑娘',p:'名',m:'girl, young lady',e:'这位姑娘汉语说得很好。',l:3},
  {w:'古',p:'形',m:'ancient, old',e:'古城市有很多老建筑。',l:3},
  {w:'古代',p:'名',m:'ancient times',e:'古代的时候，人们没有手机。',l:3},
  {w:'故乡',p:'名',m:'hometown',e:'我的故乡在南方。',l:3},
  {w:'挂',p:'动',m:'hang',e:'把衣服挂在衣架上。',l:3},
  {w:'关系',p:'名、动',m:'relationship; relate',e:'我们关系非常好。',l:3},
  {w:'关注',p:'动',m:'pay attention to',e:'关注中文新闻。',l:3},
  {w:'观察',p:'动',m:'observe',e:'观察中国人的日常对话。',l:3},
  {w:'观看',p:'动',m:'watch',e:'观看中文电影练习听力。',l:3},
  {w:'观念',p:'名',m:'idea, concept',e:'新旧观念不一样。',l:3},
  {w:'观众',p:'名',m:'audience, viewer',e:'观众喜欢这部电视剧。',l:3},
  {w:'管',p:'动',m:'manage, control',e:'老师管班级的纪律。',l:3},
  {w:'管理',p:'动',m:'manage',e:'管理学校的图书馆。',l:3},
  {w:'光',p:'副、名、形',m:'only; light; bright',e:'房间里的灯光很亮。',l:3},
  {w:'光明',p:'形、名',m:'bright; light',e:'前途一片光明。',l:3},
  {w:'广播',p:'动、名',m:'broadcast; radio',e:'广播播放着中文故事。',l:3},
  {w:'广大',p:'形',m:'vast, wide',e:'广大学生都喜欢汉语课。',l:3},
  {w:'规定',p:'动、名',m:'rule; regulate',e:'学校有很多规定。',l:3},
  {w:'规范',p:'形、名、动',m:'standard; norm; standardize',e:'我们要规范汉字书写。',l:3},
  {w:'国内',p:'名',m:'domestic, home country',e:'国内旅游很方便。',l:3},
  {w:'国庆',p:'名',m:'National Day',e:'国庆放假七天。',l:3},
  {w:'果然',p:'副',m:'sure enough, indeed',e:'果然，他准时来到了教室。',l:3},
  {w:'果汁',p:'名',m:'fruit juice',e:'果汁很好喝。',l:3},
  {w:'过程',p:'名',m:'process, course',e:'学习汉语的过程很漫长。',l:3},
  {w:'过去',p:'名',m:'past',e:'过去我不会说汉语。',l:3},
  {w:'哈哈',p:'拟声',m:'haha (laugh)',e:'哈哈，这件事太有趣了。',l:3},
  {w:'海关',p:'名',m:'customs',e:'出国要经过海关检查。',l:3},
  {w:'害怕',p:'动',m:'fear, be afraid',e:'我害怕考试不及格。',l:3},
  {w:'行',p:'量',m:'line, row',e:'我在纸上写了一行汉字。',l:3},
  {w:'好好',p:'形、副',m:'good; well',e:'好好练习汉语。',l:3},
  {w:'好奇',p:'形',m:'curious',e:'我很好奇中国文化。',l:3},
  {w:'合',p:'动',m:'combine, fit',e:'两张桌子合在一起。',l:3},
  {w:'合法',p:'形',m:'legal, lawful',e:'做合法的工作。',l:3},
  {w:'合格',p:'形',m:'qualified, up to standard',e:'考试六十分才算合格。',l:3},
  {w:'合理',p:'形',m:'reasonable',e:'这个学习计划很合理。',l:3},
  {w:'合作',p:'动',m:'cooperate, work together',e:'小组合作完成练习。',l:3},
  {w:'和平',p:'名',m:'peace',e:'世界需要和平。',l:3},
  {w:'红茶',p:'名',m:'black tea',e:'早上喝一杯红茶。',l:3},
  {w:'红酒',p:'名',m:'red wine',e:'晚餐搭配红酒。',l:3},
  {w:'后果',p:'名',m:'consequence',e:'不复习的后果是无法通过考试。',l:3},
  {w:'后面',p:'名',m:'back, behind',e:'椅子后面放书包。',l:3},
  {w:'后年',p:'名',m:'the year after next',e:'后年我回国。',l:3},
  {w:'互联网',p:'名',m:'Internet',e:'用互联网学习汉语很方便。',l:3},
  {w:'互相',p:'副',m:'each other, mutually',e:'我们互相帮助学习生词。',l:3},
  {w:'划船',p:'动',m:'row a boat',e:'周末去公园划船。',l:3},
  {w:'华人',p:'名',m:'overseas Chinese',e:'海外华人喜欢中文。',l:3},
  {w:'化',p:'后缀',m:'-ize, -ification',e:'现代化城市发展得很快。',l:3},
  {w:'话剧',p:'名',m:'stage play',e:'周末去看中文话剧。',l:3},
  {w:'话题',p:'名',m:'topic',e:'聊天的话题是中国美食。',l:3},
  {w:'欢乐',p:'形',m:'happy, joyful',e:'节日气氛十分欢乐。',l:3},
  {w:'环',p:'名',m:'ring, circle',e:'手环戴在手上。',l:3},
  {w:'环保',p:'名、形',m:'environmental protection; eco-friendly',e:'环保塑料袋可以重复用。',l:3},
  {w:'环境',p:'名',m:'environment',e:'我们要爱护教室的桌椅。',l:3},
  {w:'会议',p:'名',m:'meeting, conference',e:'下午两点开班级会议。',l:3},
  {w:'会员',p:'名',m:'member',e:'图书馆会员可以借书。',l:3},
  {w:'活',p:'形、动',m:'alive; live',e:'这里的小动物都是活的。',l:3},
  {w:'火',p:'名',m:'fire',e:'人们用火做饭。',l:3},
  {w:'机器',p:'名',m:'machine',e:'这台机器用来打印资料。',l:3},
  {w:'积极',p:'形',m:'active',e:'课堂上积极回答问题。',l:3},
  {w:'基本',p:'形',m:'basic',e:'掌握基本的汉语词汇。',l:3},
  {w:'基本上',p:'副',m:'basically, mostly',e:'基本上每天都学习汉语。',l:3},
  {w:'基础',p:'名',m:'foundation',e:'打好汉语基础很关键。',l:3},
  {w:'及时',p:'形',m:'timely',e:'及时完成作业。',l:3},
  {w:'… 极了',p:'短语',m:'extremely',e:'今天开心极了。',l:3},
  {w:'集体',p:'名',m:'group, collective',e:'集体一起去博物馆。',l:3},
  {w:'集中',p:'动、形',m:'gather; concentrated',e:'集中注意力听老师讲课。',l:3},
  {w:'计算',p:'动',m:'calculate, count',e:'计算一共多少个生词。',l:3},
  {w:'记录',p:'名、动',m:'record; write down',e:'记录每天学到的生词。',l:3},
  {w:'记者',p:'名',m:'journalist, reporter',e:'记者采访汉语留学生。',l:3},
  {w:'纪录',p:'名',m:'record',e:'打破跑步世界纪录。',l:3},
  {w:'纪念',p:'动、名',m:'commemorate; memory',e:'纪念传统节日。',l:3},
  {w:'技术',p:'名',m:'technology, skill',e:'学习电脑技术。',l:3},
  {w:'继续',p:'动',m:'continue',e:'继续朗读汉语课文。',l:3},
  {w:'加工',p:'动',m:'process, make',e:'加工水果做成果汁。',l:3},
  {w:'加快',p:'动',m:'speed up',e:'加快背单词的速度。',l:3},
  {w:'加强',p:'动',m:'strengthen',e:'加强汉语听力练习。',l:3},
  {w:'家具',p:'名',m:'furniture',e:'房间里有简单家具。',l:3},
  {w:'家属',p:'名',m:'family members',e:'家属可以来学校参观。',l:3},
  {w:'家乡',p:'名',m:'hometown',e:'我的家乡风景很美。',l:3},
  {w:'价格',p:'名',m:'price',e:'这件衣服价格不贵。',l:3},
  {w:'价钱',p:'名',m:'price',e:'饭店饭菜价钱合理。',l:3},
  {w:'价值',p:'名',m:'value',e:'这本书很有学习价值。',l:3},
  {w:'架',p:'量、名、动',m:'shelf; frame; put on',e:'一架飞机飞过天空。',l:3},
  {w:'坚持',p:'动',m:'persist, insist',e:'坚持每天学习一小时汉语。',l:3},
  {w:'坚决',p:'形',m:'firm, resolute',e:'我坚决每天早起读书。',l:3},
  {w:'坚强',p:'形',m:'strong, tough',e:'遇到困难要坚强。',l:3},
  {w:'简单',p:'形',m:'simple',e:'这个句子语法很简单。',l:3},
  {w:'简直',p:'副',m:'simply, almost',e:'简直不敢相信汉语这么有趣。',l:3},
  {w:'建',p:'动',m:'build, construct',e:'建一座新教学楼。',l:3},
  {w:'建成',p:'动',m:'finish building',e:'新图书馆今年建成。',l:3},
  {w:'建立',p:'动',m:'establish, build',e:'建立汉语学习小组。',l:3},
  {w:'建设',p:'动、名',m:'build; construction',e:'建设美丽的城市。',l:3},
  {w:'建议',p:'动、名',m:'suggest; suggestion',e:'老师给我了很好的学习建议。',l:3},
  {w:'将近',p:'副',m:'nearly, almost',e:'将近一百名留学生。',l:3},
  {w:'将来',p:'名',m:'future',e:'将来我想在中国工作。',l:3},
  {w:'交费',p:'动',m:'pay fees',e:'每个月按时交费。',l:3},
  {w:'交警',p:'名',m:'traffic police',e:'交警指挥路上的车辆。',l:3},
  {w:'交流',p:'动、名',m:'communicate; exchange',e:'和中国朋友交流汉语。',l:3},
  {w:'交往',p:'动',m:'contact, interact',e:'多和本地人交往提高口语。',l:3},
  {w:'交易',p:'名',m:'deal, trade',e:'市场上每天有很多交易。',l:3},
  {w:'叫',p:'介',m:'by, called',e:'他叫小明。',l:3},
  {w:'较',p:'副',m:'comparatively',e:'这件衣服较便宜。',l:3},
  {w:'教材',p:'名',m:'textbook',e:'三级汉语教材很实用。',l:3},
  {w:'教练',p:'名',m:'coach, trainer',e:'篮球教练教我们打球。',l:3},
  {w:'结实',p:'形',m:'solid, strong',e:'这个书包很结实耐用。',l:3},
  {w:'接待',p:'动',m:'receive, welcome',e:'接待来参观的客人。',l:3},
  {w:'接近',p:'动',m:'close to, approach',e:'他经常欺负同学，谁也不愿意接近他。',l:3},
  {w:'节约',p:'动',m:'save, economize',e:'节约水和粮食。',l:3},
  {w:'结合',p:'动',m:'combine, combine together',e:'结合课文记生词。',l:3},
  {w:'结婚',p:'动',m:'get married',e:'他们明年打算结婚。',l:3},
  {w:'结束',p:'动',m:'end, finish',e:'下午五点课程结束。',l:3},
  {w:'解决',p:'动',m:'solve, resolve',e:'解决学习里的难题。',l:3},
  {w:'解开',p:'动',m:'untie, solve',e:'你把绳子解开吧。',l:3},
  {w:'金',p:'名',m:'gold',e:'金色的奖牌很好看。',l:3},
  {w:'金牌',p:'名',m:'gold medal',e:'比赛第一名得到金牌。',l:3},
  {w:'仅',p:'副',m:'only, merely',e:'仅需要十分钟写完练习。',l:3},
  {w:'仅仅',p:'副',m:'only, just',e:'仅仅认识一百个汉字。',l:3},
  {w:'尽量',p:'副',m:'try one\'s best',e:'尽量多说汉语不要害怕。',l:3},
  {w:'紧',p:'形',m:'tight',e:'衣服有点紧，不太舒服。',l:3},
  {w:'紧急',p:'形',m:'urgent, emergency',e:'有紧急事情马上打电话。',l:3},
  {w:'紧张',p:'形',m:'nervous, tense',e:'考试前我有点紧张。',l:3},
  {w:'进步',p:'动、形',m:'make progress; progressive',e:'我的汉语每天都在进步。',l:3},
  {w:'进一步',p:'副',m:'further, more',e:'进一步提高口语水平。',l:3},
  {w:'进展',p:'动',m:'make progress',e:'工作有进展了吗？',l:3},
  {w:'近期',p:'名',m:'recent period',e:'近期有汉语演讲比赛。',l:3},
  {w:'京剧',p:'名',m:'Peking Opera',e:'周末看一场京剧。',l:3},
  {w:'经济',p:'名、形',m:'economy; economic',e:'这座城市经济发达。',l:3},
  {w:'经历',p:'动、名',m:'experience; experience',e:'我亲身经历过两次战争。',l:3},
  {w:'经验',p:'名',m:'experience',e:'他刚大学毕业，没有什么经验。',l:3},
  {w:'经营',p:'动',m:'manage, run',e:'他经营一家小饭店。',l:3},
  {w:'精彩',p:'形',m:'wonderful, brilliant',e:'这场表演十分精彩。',l:3},
  {w:'精神',p:'名',m:'spirit, mind',e:'精神很好，上课不犯困。',l:3},
  {w:'精神',p:'形、名',m:'energetic; spirit',e:'早上起来很精神。',l:3},
  {w:'景色',p:'名',m:'scenery, view',e:'山里景色非常美丽。',l:3},
  {w:'警察',p:'名',m:'police officer',e:'路上有警察维持秩序。',l:3},
  {w:'静',p:'形、动',m:'quiet; calm down',e:'教室保持安静。',l:3},
  {w:'久',p:'形',m:'long (time)',e:'][很久没有见到朋友。',l:3},
  {w:'旧',p:'形',m:'old, used',e:'旧衣服可以回收。',l:3},
  {w:'救',p:'动',m:'save, rescue',e:'救人是好事。',l:3},
  {w:'就是',p:'连',m:'just, exactly',e:'这就是我的汉语课本。',l:3},
  {w:'就业',p:'动',m:'find a job',e:'毕业后在中国就业。',l:3},
  {w:'举办',p:'动',m:'hold, organize',e:'学校举办汉语比赛。',l:3},
  {w:'具体',p:'形',m:'specific, concrete',e:'说具体一点，我听不懂。',l:3},
  {w:'具有',p:'动',m:'have, possess',e:'手机具有上网的功能。',l:3},
  {w:'剧场',p:'名',m:'theater',e:'剧场里正在演话剧。',l:3},
  {w:'据说',p:'动',m:'it is said',e:'据说这里美食很好吃。',l:3},
  {w:'决定',p:'动、名',m:'decide; decision',e:'我决定每天多背生词。',l:3},
  {w:'决赛',p:'动、名',m:'final match',e:'明天进行决赛。',l:3},
  {w:'决心',p:'名、动',m:'determination; resolve',e:'学好汉语的决心不会变。',l:3},
  {w:'绝对',p:'副',m:'absolutely, definitely',e:'我绝对不会迟到。',l:3},
  {w:'咖啡',p:'名',m:'coffee',e:'早上喝一杯咖啡提神。',l:3},
  {w:'开发',p:'动',m:'develop, exploit',e:'开发新的汉语学习软件。',l:3},
  {w:'开放',p:'动',m:'open, open up',e:'图书馆每天八点开放。',l:3},
  {w:'开始',p:'动、名',m:'start; beginning',e:'课程九点开始。',l:3},
  {w:'开业',p:'动',m:'open for business',e:'这家饭店今天开业。',l:3},
  {w:'开展',p:'动',m:'carry out, develop',e:'开展汉语交流活动。',l:3},
  {w:'看起来',p:'动',m:'look, seem',e:'这件衣服看起来很好看。',l:3},
  {w:'看上去',p:'动',m:'look, appear',e:'他看上去很开心。',l:3},
  {w:'考验',p:'动',m:'test, trial',e:'困难考验我们的耐心。',l:3},
  {w:'科技',p:'名',m:'technology',e:'科技让学习更方便。',l:3},
  {w:'可靠',p:'形',m:'reliable, trustworthy',e:'这位老师很可靠。',l:3},
  {w:'可乐',p:'名',m:'cola',e:'夏天喝可乐很凉快。',l:3},
  {w:'克服',p:'动',m:'overcome',e:'克服害怕说汉语的心理。',l:3},
  {w:'客观',p:'形',m:'objective',e:'客观看待自己的汉语水平。',l:3},
  {w:'课程',p:'名',m:'course, lesson',e:'一周有五节汉语课程。',l:3},
  {w:'空',p:'形、副',m:'empty; free',e:'房间现在是空的。',l:3},
  {w:'空调',p:'名',m:'air conditioner',e:'夏天开空调降温。',l:3},
  {w:'恐怕',p:'副',m:'afraid, probably',e:'恐怕今天会下雨。',l:3},
  {w:'空儿',p:'名',m:'free time',e:'有空儿一起去逛街。',l:3},
  {w:'裤子',p:'名',m:'trousers, pants',e:'这条裤子很合身。',l:3},
  {w:'快速',p:'形',m:'fast, quick',e:'快速记住生词。',l:3},
  {w:'困',p:'形、动',m:'sleepy; feel tired',e:'晚上学习久了很困。',l:3},
  {w:'困难',p:'名、形',m:'difficulty; difficult',e:'学习汉语没有困难。',l:3},
  {w:'浪费',p:'动',m:'waste',e:'不要浪费粮食和水。',l:3},
  {w:'老百姓',p:'名',m:'common people',e:'老百姓喜欢简单的生活。',l:3},
  {w:'老板',p:'名',m:'boss, shop owner',e:'饭店老板人很好。',l:3},
  {w:'老太太',p:'名',m:'old lady',e:'老太太喜欢散步。',l:3},
  {w:'老头儿',p:'名',m:'old man',e:'老头儿每天早上打太极。',l:3},
  {w:'乐',p:'动',m:'happy, enjoy',e:'看到小狗的样子，大家都乐了。',l:3},
  {w:'乐观',p:'形',m:'optimistic',e:'遇到困难保持乐观。',l:3},
  {w:'类',p:'名、量',m:'kind, type; category',e:'各类中文书籍放在书架。',l:3},
  {w:'类似',p:'动、形',m:'similar; resemble',e:'你的问题和我的问题非常类似。',l:3},
  {w:'离婚',p:'动',m:'divorce',e:'他上个月跟老婆离婚了。',l:3},
  {w:'里面',p:'名',m:'inside',e:'书包里面有课本。',l:3},
  {w:'理发',p:'动',m:'get a haircut',e:'周末去理发店理发。',l:3},
  {w:'理解',p:'动',m:'understand',e:'理解课文里的意思。',l:3},
  {w:'理论',p:'名',m:'theory',e:'语言理论可以帮助学好汉语。',l:3},
  {w:'理由',p:'名',m:'reason, excuse',e:'说出迟到的理由。',l:3},
  {w:'力',p:'名',m:'power, strength',e:'他力量很大。',l:3},
  {w:'力量',p:'名',m:'strength, power',e:'朋友的鼓励给了我力量。',l:3},
  {w:'立刻',p:'副',m:'immediately, right away',e:'立刻拿出课本朗读。',l:3},
  {w:'利用',p:'动',m:'use, make use of',e:'利用空闲时间背单词。',l:3},
  {w:'连',p:'动、副',m:'connect; even',e:'连最简单的句子我都会说。',l:3},
  {w:'连忙',p:'副',m:'hurriedly, quickly',e:'连忙站起来回答老师问题。',l:3},
  {w:'连续',p:'动',m:'continuous, successive',e:'连续三天练习听力。',l:3},
  {w:'连续剧',p:'名',m:'TV series',e:'晚上看中文连续剧。',l:3},
  {w:'联合',p:'动',m:'unite, combine',e:'两国学校联合举办比赛。',l:3},
  {w:'联合国',p:'名',m:'the United Nations',e:'联合国总部在美国。',l:3},
  {w:'联系',p:'动、名',m:'contact; connection',e:'经常联系中国朋友。',l:3},
  {w:'凉水',p:'名',m:'cold water',e:'夏天喝凉水很舒服。',l:3},
  {w:'了',p:'助',m:'perfect particle',e:'我吃完晚饭了。',l:3},
  {w:'领',p:'动',m:'lead, get',e:'领新的汉语课本。',l:3},
  {w:'领导',p:'动、名',m:'lead; leader',e:'领导组织班级活动。',l:3},
  {w:'领先',p:'动',m:'take the lead',e:'她在跑步比赛中一直领先。',l:3},
  {w:'另外',p:'代、副、连',m:'other; besides',e:'另外还有一本练习册。',l:3},
  {w:'另一方面',p:'短语',m:'on the other hand',e:'一方面读书，另一方面多开口。',l:3},
  {w:'留学',p:'动',m:'study abroad',e:'来中国留学两年。',l:3},
  {w:'龙',p:'名',m:'dragon',e:'龙是中国传统象征。',l:3},
  {w:'录',p:'动',m:'record',e:'录下老师的讲课音频。',l:3},
  {w:'录音',p:'动、名',m:'record; recording',e:'用录音练习汉语发音。',l:3},
  {w:'路线',p:'名',m:'route, path',e:'规划去长城的路线。',l:3},
  {w:'旅馆',p:'名',m:'hotel, inn',e:'外出住便宜旅馆。',l:3},
  {w:'旅行社',p:'名',m:'travel agency',e:'旅行社安排旅游行程。',l:3},
  {w:'绿茶',p:'名',m:'green tea',e:'饭后喝绿茶很舒服。',l:3},
  {w:'乱',p:'形',m:'messy, disorderly',e:'房间不要弄得很乱。',l:3},
  {w:'落后',p:'动',m:'fall behind',e:'不要落后于同学。',l:3},
  {w:'麻烦',p:'动、形',m:'trouble; troublesome',e:'这件事有点麻烦。',l:3},
  {w:'马',p:'名',m:'horse',e:'公园里有小马。',l:3},
  {w:'满足',p:'动',m:'satisfy, content',e:'每天进步一点我就很满足了。',l:3},
  {w:'慢慢',p:'副',m:'slowly',e:'慢慢读汉字，读准发音。',l:3},
  {w:'毛',p:'名',m:'hair, fur',e:'小猫的毛很软。',l:3},
  {w:'毛病',p:'名',m:'fault, problem',e:'他有个坏毛病，就是老说假话。',l:3},
  {w:'没用',p:'形',m:'useless',e:'这个旧本子已经没用了。',l:3},
  {w:'媒体',p:'名',m:'media',e:'电视是很多人熟悉的一种媒体。',l:3},
  {w:'每',p:'代、副',m:'every, each',e:'每天早上朗读课文。',l:3},
  {w:'美',p:'形',m:'beautiful, nice',e:'中国风景很美。',l:3},
  {w:'美好',p:'形',m:'nice, wonderful',e:'美好的生活需要努力。',l:3},
  {w:'美丽',p:'形',m:'beautiful',e:'美丽的花朵开在公园。',l:3},
  {w:'美食',p:'名',m:'delicious food',e:'各地有不同美食。',l:3},
  {w:'美术',p:'名',m:'art, fine arts',e:'美术课画中国画。',l:3},
  {w:'美元',p:'名',m:'US dollar',e:'美元兑换人民币。',l:3},
  {w:'迷',p:'动',m:'be crazy about',e:'我迷上了中文电视剧。',l:3},
  {w:'米',p:'名',m:'rice, meter',e:'我能吃一碗米。',l:3},
  {w:'面对',p:'动',m:'face, confront',e:'面对困难不要害怕。',l:3},
  {w:'面积',p:'名',m:'area',e:'这间教室面积很大。',l:3},
  {w:'民间',p:'名',m:'folk, among people',e:'民间有很多有趣故事。',l:3},
  {w:'民族',p:'名',m:'nation, ethnic group',e:'中国有很多民族。',l:3},
  {w:'明确',p:'形、动',m:'clear; make clear',e:'明确每天的学习计划。',l:3},
  {w:'明显',p:'形',m:'obvious, clear',e:'进步效果很明显。',l:3},
  {w:'命运',p:'名',m:'destiny, fate',e:'努力改变自己的命运。',l:3},
  {w:'某',p:'代',m:'certain, some',e:'某天我们一起去吃饭。',l:3},
  {w:'母亲',p:'名',m:'mother',e:'我的母亲喜欢做饭。',l:3},
  {w:'木头',p:'名',m:'wood, wood log',e:'木头桌子很结实。',l:3},
  {w:'目标',p:'名',m:'goal, target',e:'学好三级汉语是我的目标。',l:3},
  {w:'目前',p:'名',m:'at present, now',e:'目前我在学习HSK三级。',l:3},
  {w:'奶茶',p:'名',m:'milk tea',e:'下午喝一杯奶茶。',l:3},
  {w:'男子',p:'名',m:'man, male person',e:'这位男子是汉语老师。',l:3},
  {w:'南部',p:'名',m:'south part',e:'南部天气温暖湿润。',l:3},
  {w:'难道',p:'副',m:'could it be that',e:'难道你不会说简单的汉语？',l:3},
  {w:'难度',p:'名',m:'difficulty',e:'三级词汇难度不大。',l:3},
  {w:'内',p:'名',m:'inside',e:'房间内禁止吃东西。',l:3},
  {w:'内容',p:'名',m:'content',e:'课文内容简单易懂。',l:3},
  {w:'内心',p:'名',m:'heart, inner mind',e:'内心喜欢中国文化。',l:3},
  {w:'能不能',p:'短语',m:'can or not',e:'能不能帮我翻译句子？',l:3},
  {w:'能力',p:'名',m:'ability, capability',e:'口语能力需要多练习。',l:3},
  {w:'年初',p:'名',m:'early year',e:'年初制定学习计划。',l:3},
  {w:'年代',p:'名',m:'age, years',e:'九十年代没有智能手机。',l:3},
  {w:'年底',p:'名',m:'end of the year',e:'年底准备汉语考试。',l:3},
  {w:'年纪',p:'名',m:'age',e:'年纪大的人学习慢一点。',l:3},
  {w:'念',p:'动',m:'read aloud',e:'念生词练习发音。',l:3},
  {w:'牛',p:'名',m:'cow, ox',e:'农场里有牛。',l:3},
  {w:'农村',p:'名',m:'village, countryside',e:'农村空气很好。',l:3},
  {w:'农民',p:'名',m:'farmer',e:'农民种植蔬菜粮食。',l:3},
  {w:'农业',p:'名',m:'agriculture',e:'中国农业发展很快。',l:3},
  {w:'女子',p:'名',m:'woman, female',e:'这位女子在中国留学。',l:3},
  {w:'暖和',p:'形',m:'warm',e:'冬天房间很暖和。',l:3},
  {w:'怕',p:'副',m:'fear, afraid',e:'怕说错汉语不敢开口。',l:3},
  {w:'拍',p:'动',m:'pat, take (photo)',e:'拍一张长城照片。',l:3},
  {w:'排',p:'动',m:'arrange, line up',e:'排队进入图书馆。',l:3},
  {w:'排名',p:'动、名',m:'rank; ranking',e:'这次考试我的排名靠前。',l:3},
  {w:'牌子',p:'名',m:'sign, board',e:'门口的牌子写教室名称。',l:3},
  {w:'派',p:'动',m:'send, assign',e:'老师派我分发练习册。',l:3},
  {w:'判断',p:'动、名',m:'judge; judgment',e:'判断句子语法对错。',l:3},
  {w:'胖',p:'形',m:'fat, plump',e:'他吃得很好，有点胖。',l:3},
  {w:'跑步',p:'动',m:'run, jog',e:'每天早上跑步锻炼身体。',l:3},
  {w:'配',p:'动',m:'match, mix',e:'搭配汉字和拼音。',l:3},
  {w:'配合',p:'动',m:'cooperate, coordinate',e:'小组配合完成对话练习。',l:3},
  {w:'批评',p:'动',m:'criticize',e:'老师批评我不认真复习。',l:3},
  {w:'批准',p:'动',m:'approve',e:'老师批准我请假一天。',l:3},
  {w:'皮',p:'名',m:'skin, leather',e:'皮包很耐用。',l:3},
  {w:'皮包',p:'名',m:'leather bag',e:'我的皮包放在桌子上。',l:3},
  {w:'啤酒',p:'名',m:'beer',e:'晚饭喝一点啤酒。',l:3},
  {w:'票价',p:'名',m:'ticket price',e:'电影票价不贵。',l:3},
  {w:'评价',p:'动、名',m:'evaluate; comment',e:'评价自己的汉语学习情况。',l:3},
  {w:'苹果',p:'名',m:'apple',e:'每天吃一个苹果。',l:3},
  {w:'破',p:'形、动',m:'broken; break',e:'杯子摔破了。',l:3},
  {w:'破坏',p:'动',m:'destroy, damage',e:'不要破坏公共设施。',l:3},
  {w:'普遍',p:'形',m:'common, widespread',e:'在大学，迟到的现象很普遍。',l:3},
  {w:'普及',p:'动、形',m:'popularize; popular',e:'普及中文教育。',l:3},
  {w:'期',p:'量',m:'period, term',e:'一期汉语班两个月。',l:3},
  {w:'齐',p:'形、动',m:'neat; align',e:'书本摆放整齐。',l:3},
  {w:'其次',p:'代',m:'next, secondly',e:'首先背单词，其次练听力。',l:3},
  {w:'其实',p:'副',m:'actually, in fact',e:'其实汉语没有那么难。',l:3},
  {w:'奇怪',p:'形',m:'strange, odd',e:'这件事有点奇怪。',l:3},
  {w:'气候',p:'名',m:'climate',e:'北方气候冬天寒冷。',l:3},
  {w:'千万',p:'副',m:'must, by all means',e:'千万不要忘记带课本。',l:3},
  {w:'前后',p:'名',m:'before and after',e:'他春节前后会回来。',l:3},
  {w:'前进',p:'动',m:'move forward, progress',e:'每天前进一小步。',l:3},
  {w:'前面',p:'名',m:'front',e:'教室前面有黑板。',l:3},
  {w:'前往',p:'动',m:'go to, head for',e:'周末前往公园游玩。',l:3},
  {w:'强',p:'形',m:'strong, powerful',e:'他口语能力很强。',l:3},
  {w:'强大',p:'形',m:'powerful, strong',e:'国家越来越强大。',l:3},
  {w:'强调',p:'动',m:'emphasize',e:'老师强调多开口说汉语。',l:3},
  {w:'强烈',p:'形',m:'strong, intense',e:'强烈的学习兴趣能帮助进步。',l:3},
  {w:'桥',p:'名',m:'bridge',e:'河上有一座大桥。',l:3},
  {w:'巧',p:'形',m:'clever, skillful',e:'他写字很巧很好看。',l:3},
  {w:'亲',p:'形',m:'close, dear',e:'亲人之间互相关心。',l:3},
  {w:'亲切',p:'形',m:'kind, warm',e:'中国人待人很亲切。',l:3},
  {w:'亲人',p:'名',m:'family member, relative',e:'亲人每年假期见面。',l:3},
  {w:'亲自',p:'副',m:'personally',e:'亲自去书店买汉语书。',l:3},
  {w:'情感',p:'名',m:'emotion, feeling',e:'文章里有丰富情感。',l:3},
  {w:'情况',p:'名',m:'situation, condition',e:'说说你的学习情况。',l:3},
  {w:'请教',p:'动',m:'ask for advice',e:'请教老师不懂的生词。',l:3},
  {w:'庆祝',p:'动',m:'celebrate',e:'庆祝春节、国庆节日。',l:3},
  {w:'球迷',p:'名',m:'sports fan',e:'他是足球球迷。',l:3},
  {w:'区',p:'名',m:'district, area',e:'学校在城市东区。',l:3},
  {w:'区别',p:'名、动',m:'difference; distinguish',e:'区别两个相近词语。',l:3},
  {w:'取消',p:'动',m:'cancel',e:'取消明天的外出活动。',l:3},
  {w:'去世',p:'动',m:'pass away',e:'老人去年去世了。',l:3},
  {w:'全场',p:'名',m:'whole audience, full place',e:'全场一起鼓掌。',l:3},
  {w:'全面',p:'形',m:'comprehensive, all-round',e:'全面练习听说读写。',l:3},
  {w:'全球',p:'名',m:'global, whole world',e:'全球越来越多人学汉语。',l:3},
  {w:'缺',p:'动',m:'lack, be short of',e:'缺一本汉语词典。',l:3},
  {w:'缺点',p:'名',m:'shortcoming, weakness',e:'胆小是我的缺点。',l:3},
  {w:'缺少',p:'动',m:'lack, miss',e:'缺少练习口语的机会。',l:3},
  {w:'确保',p:'动',m:'ensure, guarantee',e:'确保每天完成学习任务。',l:3},
  {w:'确定',p:'形、动',m:'certain; confirm',e:'确定明天上课时间。',l:3},
  {w:'确实',p:'形、副',m:'real; indeed',e:'汉语确实很有趣。',l:3},
  {w:'裙子',p:'名',m:'skirt',e:'她穿了一条红色裙子。',l:3},
  {w:'群',p:'量',m:'group, crowd',e:'一群留学生一起上课。',l:3},
  {w:'热爱',p:'动',m:'love deeply',e:'热爱中国文化。',l:3},
  {w:'热烈',p:'形',m:'warm, enthusiastic',e:'热烈欢迎新同学。',l:3},
  {w:'人才',p:'名',m:'talent, talented person',e:'汉语人才越来越多。',l:3},
  {w:'人工',p:'名、形',m:'manual; artificial',e:'人工制作的手工艺品。',l:3},
  {w:'人类',p:'名',m:'human mankind',e:'人类使用语言交流。',l:3},
  {w:'人民',p:'名',m:'people',e:'人民生活越来越好。',l:3},
  {w:'人民币',p:'名',m:'RMB, Chinese yuan',e:'人民币是中国货币。',l:3},
  {w:'人群',p:'名',m:'crowd, group of people',e:'人群聚集在广场。',l:3},
  {w:'人生',p:'名',m:'life, life journey',e:'我们可以通过努力创造美好的人生。',l:3},
  {w:'人员',p:'名',m:'staff, personnel',e:'学校工作人员很热心。',l:3},
  {w:'认出',p:'动',m:'recognize',e:'在街上认出我的同学。',l:3},
  {w:'认得',p:'动',m:'know, recognize',e:'我认得这个汉字。',l:3},
  {w:'认可',p:'动',m:'approve, recognize',e:'大家认可这个学习方法。',l:3},
  {w:'任¹',p:'连',m:'no matter',e:'任谁都要遵守规则。',l:3},
  {w:'任²',p:'代',m:'any, whatever',e:'任何人都要按时完成作业。',l:3},
  {w:'任何',p:'代',m:'any, whichever',e:'任何问题都可以问老师。',l:3},
  {w:'任务',p:'名',m:'task, assignment',e:'今天的任务是背诵生词。',l:3},
  {w:'仍',p:'副',m:'still',e:'他仍坚持每天练习汉语。',l:3},
  {w:'仍然',p:'副',m:'still, yet',e:'仍然有很多生词不会读。',l:3},
  {w:'日常',p:'形',m:'daily, everyday',e:'日常对话简单实用。',l:3},
  {w:'容易',p:'形',m:'easy',e:'三级汉语句子很容易理解。',l:3},
  {w:'如何',p:'代',m:'how',e:'如何快速记住汉字？',l:3},
  {w:'散步',p:'动',m:'take a walk',e:'晚饭后公园散步。',l:3},
  {w:'沙发',p:'名',m:'sofa, couch',e:'客厅放一张沙发。',l:3},
  {w:'沙子',p:'名',m:'sand',e:'海边有很多沙子。',l:3},
  {w:'伤',p:'动、名',m:'hurt; wound',e:'小心不要伤到手。',l:3},
  {w:'伤心',p:'动',m:'sad, heartbroken',e:'考试不好不要伤心。',l:3},
  {w:'商品',p:'名',m:'goods, product',e:'超市商品种类多。',l:3},
  {w:'商业',p:'名',m:'business, commerce',e:'这座城市商业发达。',l:3},
  {w:'上来',p:'动',m:'come up',e:'我马上下来。',l:3},
  {w:'上面',p:'名',m:'above, top',e:'桌子上面放课本。',l:3},
  {w:'上去',p:'动',m:'go up',e:'我马上上去。',l:3},
  {w:'上升',p:'动',m:'rise, go up',e:'气温慢慢上升。',l:3},
  {w:'上衣',p:'名',m:'jacket, top',e:'这件上衣很好搭配裤子。',l:3},
  {w:'设备',p:'名',m:'equipment, device',e:'教室有听力设备。',l:3},
  {w:'设计',p:'动、名',m:'design; design work',e:'设计简单的汉语练习。',l:3},
  {w:'设立',p:'动',m:'set up, establish',e:'学校设立汉语角。',l:3},
  {w:'社会',p:'名',m:'society',e:'社会需要会汉语的人。',l:3},
  {w:'身份证',p:'名',m:'ID card',e:'出门带好身份证。',l:3},
  {w:'深',p:'形',m:'deep',e:'河水很深，不要靠近。',l:3},
  {w:'深刻',p:'形',m:'deep, profound',e:'老师说的话很深刻。',l:3},
  {w:'深入',p:'动、形',m:'go deep into; thorough',e:'深入学习中国文化。',l:3},
  {w:'升',p:'动',m:'rise, go up',e:'太阳从东边升起来。',l:3},
  {w:'生',p:'形',m:'raw, fresh',e:'生肉应该放在冰箱里保存。',l:3},
  {w:'生产',p:'动',m:'produce, make',e:'工厂生产文具。',l:3},
  {w:'生存',p:'动',m:'survive',e:'没有水，鱼就无法生存。',l:3},
  {w:'生动',p:'形',m:'vivid, lively',e:'生动的课文好理解。',l:3},
  {w:'生命',p:'名',m:'life',e:'珍惜自己的生命。',l:3},
  {w:'生意',p:'名',m:'business, shop trade',e:'他做水果生意。',l:3},
  {w:'生长',p:'动',m:'grow, grow up',e:'小树慢慢生长。',l:3},
  {w:'声明',p:'动、名',m:'state; statement',e:'他声明会按时上课。',l:3},
  {w:'胜',p:'动',m:'win, beat',e:'比赛我们胜了对方。',l:3},
  {w:'胜利',p:'动、名',m:'win; victory',e:'赢得比赛胜利。',l:3},
  {w:'失去',p:'动',m:'lose',e:'不要失去学习的机会。',l:3},
  {w:'石头',p:'名',m:'stone, rock',e:'路边有一块大石头。',l:3},
  {w:'石油',p:'名',m:'oil, petroleum',e:'石油是重要资源。',l:3},
  {w:'时',p:'名',m:'time, hour',e:'平时每天学习两小时。',l:3},
  {w:'时代',p:'名',m:'times, era',e:'网络时代学汉语更方便。',l:3},
  {w:'时刻',p:'名',m:'moment, time',e:'时刻记住多开口。',l:3},
  {w:'实际上',p:'副',m:'actually, in fact',e:'实际上他汉语很好。',l:3},
  {w:'实力',p:'名',m:'strength, real ability',e:'这所大学综合实力很强。',l:3},
  {w:'实行',p:'动',m:'implement, carry out',e:'实行每日背诵计划。',l:3},
  {w:'实验',p:'动、名',m:'experiment; test',e:'他们正在做实验。',l:3},
  {w:'实验室',p:'名',m:'lab, laboratory',e:'听力实验室有耳机。',l:3},
  {w:'食品',p:'名',m:'food, food product',e:'超市各类食品齐全。',l:3},
  {w:'使',p:'动',m:'make, cause',e:'他这样做使我很生气。',l:3},
  {w:'始终',p:'副',m:'always, all along',e:'始终坚持学习汉语。',l:3},
  {w:'世纪',p:'名',m:'century',e:'二十一世纪汉语流行全球。',l:3},
  {w:'世界',p:'名',m:'world',e:'世界各地有人学中文。',l:3},
  {w:'世界杯',p:'名',m:'World Cup',e:'四年举办一次世界杯。',l:3},
  {w:'市场',p:'名',m:'market, market place',e:'菜市场有新鲜蔬菜。',l:3},
  {w:'事故',p:'名',m:'accident, incident',e:'路上注意避免事故。',l:3},
  {w:'事件',p:'名',m:'event, incident',e:'中国历史上发生过很多重大事件。',l:3},
  {w:'事实',p:'名',m:'fact',e:'事实证明努力有回报。',l:3},
  {w:'事实上',p:'副',m:'in fact, actually',e:'事实上生词不难记。',l:3},
  {w:'事业',p:'名',m:'career, cause',e:'汉语教学是很好的事业。',l:3},
  {w:'试题',p:'名',m:'test question',e:'复习全部试题准备考试。',l:3},
  {w:'试验',p:'动',m:'test, try out',e:'试验新的学习方法。',l:3},
  {w:'适合',p:'动',m:'suit, fit',e:'这个课程适合初级学生。',l:3},
  {w:'适应',p:'动',m:'adapt, get used to',e:'适应中国生活习惯。',l:3},
  {w:'适用',p:'动',m:'apply, be suitable for',e:'这种教学方法适用于高年级教学。',l:3},
  {w:'室',p:'名',m:'room, chamber',e:'学校有教室和阅览室。',l:3},
  {w:'收费',p:'动',m:'charge fees',e:'图书馆借书不收费。',l:3},
  {w:'收看',p:'动',m:'watch (TV)',e:'收看中文新闻节目。',l:3},
  {w:'收听',p:'动',m:'listen to (radio)',e:'收听中文广播练听力。',l:3},
  {w:'收音机',p:'名',m:'radio',e:'老式收音机播放歌曲。',l:3},
  {w:'手续',p:'名',m:'procedure, formalities',e:'办理入学手续。',l:3},
  {w:'手指',p:'名',m:'finger',e:'用手指指着汉字朗读。',l:3},
  {w:'首都',p:'名',m:'capital city',e:'北京是中国的首都。',l:3},
  {w:'首先',p:'副',m:'first, firstly',e:'首先复习昨天生词。',l:3},
  {w:'受',p:'动',m:'receive, suffer',e:'受老师表扬很开心。',l:3},
  {w:'受伤',p:'动',m:'get hurt',e:'运动要小心，不要受伤。',l:3},
  {w:'书架',p:'名',m:'bookshelf',e:'书架摆满了中文书。',l:3},
  {w:'输',p:'动',m:'lose, transmit',e:'比赛输了不要难过。',l:3},
  {w:'输入',p:'动',m:'input',e:'电脑输入汉字，练习书写。',l:3},
  {w:'熟人',p:'名',m:'acquaintance, friend',e:'街上遇到熟人要打招呼。',l:3},
  {w:'属',p:'动',m:'belong to',e:'这本书属于图书馆。',l:3},
  {w:'属于',p:'动',m:'belong to',e:'长城属于中国著名景点。',l:3},
  {w:'束',p:'量',m:'bundle, bunch',e:'送给老师一束鲜花。',l:3},
  {w:'数量',p:'名',m:'quantity, amount',e:'生词数量一共九百多。',l:3},
  {w:'双',p:'量、形',m:'pair; double',e:'一双鞋子、一双筷子。',l:3},
  {w:'双方',p:'名',m:'both sides',e:'双方要友好交流学习。',l:3},
  {w:'思想',p:'名',m:'thought, idea',e:'文章表达了作者的思想。',l:3},
  {w:'死',p:'动、形',m:'die; dead',e:'她丈夫死了。',l:3},
  {w:'速度',p:'名',m:'speed',e:'朗读速度不要太快。',l:3},
  {w:'随',p:'动',m:'follow, with',e:'我随朋友去了北京。',l:3},
  {w:'所',p:'名、量',m:'place; location',e:'场所、住所。',l:3},
  {w:'所长',p:'名',m:'director, head',e:'图书馆所长管理图书。',l:3},
  {w:'台',p:'名、量',m:'platform; set',e:'一台电脑、一台电视。',l:3},
  {w:'谈',p:'动',m:'talk, chat',e:'和同学谈学习计划。',l:3},
  {w:'谈话',p:'动',m:'talk, conversation',e:'今天领导找我谈话了。',l:3},
  {w:'谈判',p:'动、名',m:'negotiate; negotiation',e:'两国代表谈判合作。',l:3},
  {w:'汤',p:'名',m:'soup',e:'晚饭喝一碗热汤。',l:3},
  {w:'糖',p:'名',m:'sugar, candy',e:'咖啡加一点糖更好喝。',l:3},
  {w:'特色',p:'名',m:'special feature, characteristic',e:'这座城市有特色的美食。',l:3},
  {w:'提前',p:'动',m:'in advance, ahead of time',e:'提前十分钟到教室。',l:3},
  {w:'提问',p:'动',m:'ask questions',e:'很多记者向这位专家提问。',l:3},
  {w:'题目',p:'名',m:'topic, question',e:'考试题目全部学过。',l:3},
  {w:'体会',p:'动、名',m:'experience; understanding',e:'体会汉字的意思。',l:3},
  {w:'体现',p:'动',m:'reflect, embody',e:'这幅画体现了画家对生活的热爱。',l:3},
  {w:'体验',p:'动',m:'experience',e:'体验中国传统节日。',l:3},
  {w:'天空',p:'名',m:'sky',e:'天空很蓝，没有云。',l:3},
  {w:'甜',p:'形',m:'sweet',e:'苹果很甜很好吃。',l:3},
  {w:'调',p:'动',m:'adjust, tune',e:'调大听力音量。',l:3},
  {w:'调整',p:'动',m:'adjust, adjust plan',e:'调整每日学习时间。',l:3},
  {w:'跳',p:'动',m:'jump, skip',e:'跳绳锻炼身体。',l:3},
  {w:'跳高',p:'动',m:'high jump',e:'体育课练习跳高。',l:3},
  {w:'跳舞',p:'动',m:'dance',e:'晚会一起跳舞唱歌。',l:3},
  {w:'跳远',p:'动',m:'long jump',e:'男生跳远成绩很好。',l:3},
  {w:'铁',p:'名',m:'iron, metal',e:'铁锅做饭很好用。',l:3},
  {w:'铁路',p:'名',m:'railway, train line',e:'铁路连接各大城市。',l:3},
  {w:'听力',p:'名',m:'listening ability',e:'每天练习听力半小时。',l:3},
  {w:'听众',p:'名',m:'audience, listener',e:'听众认真听广播故事。',l:3},
  {w:'停止',p:'动',m:'stop, cease',e:'因为天气原因，所有比赛都停止了。',l:3},
  {w:'通常',p:'副',m:'usually, normally',e:'通常早上八点上课。',l:3},
  {w:'通信',p:'动',m:'communicate, correspond',e:'他们互相交换了通信地址。',l:3},
  {w:'同意',p:'动',m:'agree, approve',e:'我同意每天多背生词。',l:3},
  {w:'痛',p:'形',m:'painful, hurt',e:'头疼影响我学习。',l:3},
  {w:'痛苦',p:'形',m:'painful, suffering',e:'不要觉得学习痛苦。',l:3},
  {w:'头',p:'名',m:'head',e:'头有点疼，休息一下。',l:3},
  {w:'头脑',p:'名',m:'mind, brain',e:'头脑清醒才能好好儿学习。',l:3},
  {w:'突出',p:'形、动',m:'prominent; stand out',e:'他口语水平很突出。',l:3},
  {w:'突然',p:'形',m:'sudden',e:'突然下起大雨。',l:3},
  {w:'图',p:'名',m:'picture, drawing',e:'课本里有很多插图。',l:3},
  {w:'图画',p:'名',m:'drawing, picture',e:'图画可以帮助理解生词。',l:3},
  {w:'土',p:'名',m:'soil, earth',e:'土里种蔬菜。',l:3},
  {w:'团',p:'名、量',m:'group; team',e:'暑假的时候我报了一个旅行团。',l:3},
  {w:'团结',p:'动',m:'unite, unite together',e:'班级同学要团结互助。',l:3},
  {w:'团体',p:'名',m:'group, organization',e:'学生团体会组织活动。',l:3},
  {w:'推动',p:'动',m:'push, promote',e:'教育能推动经济的发展。',l:3},
  {w:'推广',p:'动',m:'promote, popularize',e:'推广汉语学习方法。',l:3},
  {w:'推进',p:'动',m:'push forward, advance',e:'推进每日朗读计划。',l:3},
  {w:'推开',p:'动',m:'push open',e:'推开教室门进来。',l:3},
  {w:'退',p:'动',m:'retreat, step back',e:'请同学们往后退。',l:3},
  {w:'退出',p:'动',m:'exit, withdraw',e:'他因为受伤，决定退出比赛。',l:3},
  {w:'退休',p:'动',m:'retire',e:'老人六十岁退休。',l:3},
  {w:'外交',p:'名',m:'diplomacy',e:'外交需要会多种语言。',l:3},
  {w:'外面',p:'名',m:'outside',e:'教室外面有花园。',l:3},
  {w:'外文',p:'名',m:'foreign language',e:'外文书籍放在二楼。',l:3},
  {w:'完美',p:'形',m:'perfect',e:'完美完成了所有练习。',l:3},
  {w:'完善',p:'形、动',m:'perfect; improve',e:'完善自己的学习笔记。',l:3},
  {w:'完整',p:'形',m:'complete, whole',e:'完整背诵整篇课文。',l:3},
  {w:'玩具',p:'名',m:'toy',e:'小朋友喜欢玩具。',l:3},
  {w:'往往',p:'副',m:'often, usually',e:'往往早上记忆力最好。',l:3},
  {w:'危害',p:'动、名',m:'harm; danger',e:'熬夜危害身体健康。',l:3},
  {w:'危险',p:'形、名',m:'dangerous; danger',e:'在河边玩耍很危险。',l:3},
  {w:'为¹',p:'动',m:'do, act',e:'为人要友好礼貌。',l:3},
  {w:'为²',p:'介',m:'for, to',e:'为朋友准备礼物。',l:3},
  {w:'围',p:'动',m:'surround, circle',e:'大家围坐在一起聊天。',l:3},
  {w:'伟大',p:'形',m:'great',e:'伟大的中国文化。',l:3},
  {w:'卫生',p:'形、名',m:'hygiene; clean',e:'保持房间卫生干净。',l:3},
  {w:'卫生间',p:'名',m:'bathroom, restroom',e:'教学楼每层有卫生间。',l:3},
  {w:'为了',p:'介',m:'for, in order to',e:'为了学好汉语努力练习。',l:3},
  {w:'温暖',p:'形、动',m:'warm; warm up',e:'温暖的阳光照进房间。',l:3},
  {w:'文化',p:'名',m:'culture',e:'学习中国传统文化。',l:3},
  {w:'文件',p:'名',m:'document, file',e:'保存好学习文件。',l:3},
  {w:'文明',p:'名、形',m:'civilization; civilized',e:'文明城市干净整洁。',l:3},
  {w:'文学',p:'名',m:'literature',e:'中文文学故事很有趣。',l:3},
  {w:'文章',p:'名',m:'article, essay',e:'写一篇简单的中文文章。',l:3},
  {w:'文字',p:'名',m:'writing, character',e:'汉字是中国文字。',l:3},
  {w:'握手',p:'动',m:'shake hands',e:'见面握手打招呼。',l:3},
  {w:'屋子',p:'名',m:'room, house',e:'这间屋子很小但干净。',l:3},
  {w:'武器',p:'名',m:'weapon',e:'博物馆展示古代武器。',l:3},
  {w:'武术',p:'名',m:'martial arts',e:'学习中国武术。',l:3},
  {w:'舞台',p:'名',m:'stage',e:'学生上舞台表演节目。',l:3},
  {w:'西部',p:'名',m:'west part',e:'中国西部风景优美。',l:3},
  {w:'希望',p:'动、名',m:'hope; wish',e:'希望汉语水平快速提高。',l:3},
  {w:'系',p:'名',m:'department, tie',e:'中文系留学生很多。',l:3},
  {w:'下来',p:'动',m:'come down',e:'从楼上下来吃饭。',l:3},
  {w:'下面',p:'名',m:'below, under',e:'桌子下面放书包。',l:3},
  {w:'下去',p:'动',m:'go down',e:'下去一楼取快递。',l:3},
  {w:'先进',p:'形、名',m:'advanced; advanced person',e:'先进的学习方法效率高。',l:3},
  {w:'显得',p:'动',m:'seem, look',e:'她站在台阶上，显得她高一点儿。',l:3},
  {w:'显然',p:'形',m:'obvious, clear',e:'显然他认真复习了。',l:3},
  {w:'显示',p:'动',m:'show, display',e:'电脑显示生词拼音。',l:3},
  {w:'现场',p:'名',m:'scene, spot',e:'比赛现场非常热闹。',l:3},
  {w:'现代',p:'名',m:'modern times',e:'现代生活离不开网络。',l:3},
  {w:'现金',p:'名',m:'cash',e:'出门带一点现金。',l:3},
  {w:'现实',p:'名',m:'reality',e:'一些人对现实世界不满意。',l:3},
  {w:'现象',p:'名',m:'phenomenon',e:'下雨是一种常见的自然现象。',l:3},
  {w:'线',p:'名',m:'line, wire',e:'电线不要随便触碰。',l:3},
  {w:'相比',p:'动',m:'compare with',e:'相比去年，我的汉语进步很多。',l:3},
  {w:'相当',p:'副、动',m:'quite; match',e:'这个手机的价钱相当于我一个月的收入。',l:3},
  {w:'相关',p:'动',m:'related, relevant',e:'相关生词放在同一单元。',l:3},
  {w:'相互',p:'副',m:'mutual, each other',e:'相互纠正发音错误。',l:3},
  {w:'相似',p:'形',m:'similar',e:'两个词语意思相似。',l:3},
  {w:'香',p:'形',m:'fragrant, tasty',e:'饭菜很香很好吃。',l:3},
  {w:'香蕉',p:'名',m:'banana',e:'香蕉香甜可口。',l:3},
  {w:'消费',p:'动',m:'consume, spend money',e:'周末出门逛街消费。',l:3},
  {w:'消失',p:'动',m:'disappear, vanish',e:'云朵慢慢消失不见。',l:3},
  {w:'消息',p:'名',m:'news, message',e:'收到朋友的消息。',l:3},
  {w:'效果',p:'名',m:'effect, result',e:'多开口练习效果很好。',l:3},
  {w:'写作',p:'动',m:'write, writing',e:'期末考试有写作。',l:3},
  {w:'血',p:'名',m:'blood',e:'受伤会流血，小心一点。',l:3},
  {w:'心',p:'名',m:'heart',e:'心里喜欢中文学习。',l:3},
  {w:'信',p:'名',m:'letter, trust',e:'写一封中文信给朋友。',l:3},
  {w:'信封',p:'名',m:'envelope',e:'信纸放进信封邮寄。',l:3},
  {w:'信任',p:'动',m:'trust',e:'她很信任她的老师。',l:3},
  {w:'行李',p:'名',m:'luggage, baggage',e:'出国带好行李。',l:3},
  {w:'形成',p:'动',m:'form, take shape',e:'长期练习形成好的汉语习惯。',l:3},
  {w:'形式',p:'名',m:'form, style',e:'用对话形式练习口语。',l:3},
  {w:'形象',p:'名、形',m:'image; vivid',e:'课文里的人物形象很生动。',l:3},
  {w:'形状',p:'名',m:'shape, form',e:'苹果是圆形的形状。',l:3},
  {w:'幸福',p:'形',m:'happy, blessed',e:'学好汉语让我感觉很幸福。',l:3},
  {w:'幸运',p:'形',m:'lucky',e:'我很幸运能来中国学汉语。',l:3},
  {w:'性',p:'后缀',m:'-ity, -ness',e:'积极性、重要性。',l:3},
  {w:'性别',p:'名',m:'gender, sex',e:'表格需要填写性别。',l:3},
  {w:'性格',p:'名',m:'personality, character',e:'他性格开朗，爱交朋友。',l:3},
  {w:'修',p:'动',m:'repair, fix',e:'修理坏了的电脑。',l:3},
  {w:'修改',p:'动',m:'revise, modify',e:'修改作文里的错误句子。',l:3},
  {w:'需求',p:'名',m:'demand, need',e:'学生有大量练习汉语的需求。',l:3},
  {w:'需要',p:'动、名',m:'need; demand',e:'我们需要每天背生词。',l:3},
  {w:'宣布',p:'动',m:'announce',e:'老师宣布下周汉语比赛安排。',l:3},
  {w:'宣传',p:'动、名',m:'promote; publicity',e:'宣传中国传统文化。',l:3},
  {w:'选手',p:'名',m:'player, contestant',e:'比赛选手准备上台演讲。',l:3},
  {w:'学费',p:'名',m:'tuition fee',e:'每年按时交学费。',l:3},
  {w:'训练',p:'动、名',m:'train; training',e:'每天听力训练半小时。',l:3},
  {w:'压',p:'动',m:'press, push down',e:'你压着我的头发了。',l:3},
  {w:'压力',p:'名',m:'pressure',e:'不要给自己太大压力。',l:3},
  {w:'烟',p:'名',m:'smoke, cigarette',e:'教室里禁止抽烟。',l:3},
  {w:'眼前',p:'名',m:'before one\'s eyes',e:'眼前就是美丽的公园。',l:3},
  {w:'演',p:'动',m:'act, perform',e:'演中文小话剧练习口语。',l:3},
  {w:'演唱',p:'动',m:'sing, perform vocally',e:'歌手演唱了经典中文歌曲。',l:3},
  {w:'演唱会',p:'名',m:'concert',e:'周末去看演唱会。',l:3},
  {w:'演出',p:'动、名',m:'perform; show',e:'学校每周有文艺演出。',l:3},
  {w:'演员',p:'名',m:'actor, performer',e:'这位演员汉语说得很流利。',l:3},
  {w:'羊',p:'名',m:'sheep',e:'山上有很多小羊。',l:3},
  {w:'阳光',p:'名',m:'sunlight',e:'阳光照进教室很温暖。',l:3},
  {w:'要是',p:'连',m:'if, suppose',e:'要是明天不下雨，我们去逛街。',l:3},
  {w:'衣架',p:'名',m:'clothes hanger',e:'把外套挂在衣架上。',l:3},
  {w:'一切',p:'代',m:'all, everything',e:'一切学习问题都可以问老师。',l:3},
  {w:'已',p:'副',m:'already',e:'我已学完三级全部生词。',l:3},
  {w:'以来',p:'名',m:'since, ever since',e:'过去三年以来，他一直在做出国留学的准备。',l:3},
  {w:'一方面',p:'名',m:'on one hand',e:'一方面多听，一方面多说。',l:3},
  {w:'艺术',p:'名',m:'art',e:'书法是中国传统艺术。',l:3},
  {w:'意外',p:'形、名',m:'unexpected; accident',e:'今天遇到一件意外的好事。',l:3},
  {w:'意义',p:'名',m:'meaning, significance',e:'学习汉语有很大意义。',l:3},
  {w:'因此',p:'连',m:'so, therefore',e:'他每天练习，因此汉语很好。',l:3},
  {w:'银',p:'名',m:'silver',e:'他得到了一枚银牌。',l:3},
  {w:'银牌',p:'名',m:'silver medal',e:'他拿到了银牌。',l:3},
  {w:'印象',p:'名',m:'impression',e:'中国给我留下了很好的印象。',l:3},
  {w:'应当',p:'动',m:'should, ought to',e:'应当每天复习生词。',l:3},
  {w:'迎接',p:'动',m:'welcome, meet',e:'去车站迎接新同学。',l:3},
  {w:'营养',p:'名',m:'nutrition',e:'蔬菜水果有丰富的营养。',l:3},
  {w:'赢',p:'动',m:'win',e:'努力练习就能赢比赛。',l:3},
  {w:'影视',p:'名',m:'film and TV works',e:'多看影视作品可以提升听力。',l:3},
  {w:'应用',p:'动',m:'apply, use',e:'把学到的词语应用在对话里。',l:3},
  {w:'优点',p:'名',m:'advantage, merit',e:'敢开口是他的优点。',l:3},
  {w:'优势',p:'名',m:'advantage, strength',e:'全场比赛我们队都保持优势。',l:3},
  {w:'由',p:'介',m:'from, by',e:'这件事由老师安排。',l:3},
  {w:'由于',p:'介、连',m:'because of, since',e:'由于学习努力，他进步很快。',l:3},
  {w:'邮件',p:'名',m:'mail, email',e:'每天查看邮件回复老师。',l:3},
  {w:'邮票',p:'名',m:'stamp',e:'寄信需要贴邮票。',l:3},
  {w:'邮箱',p:'名',m:'mailbox',e:'信件放进楼下邮箱了。',l:3},
  {w:'游',p:'动',m:'travel, swim',e:'假期准备去长城旅游。',l:3},
  {w:'游戏',p:'名',m:'game',e:'课间玩简单中文游戏。',l:3},
  {w:'游泳',p:'名、动',m:'swim; swimming',e:'夏天去泳池游泳。',l:3},
  {w:'有的是',p:'短语',m:'there are plenty of',e:'汉语练习材料有的是。',l:3},
  {w:'有利',p:'形',m:'beneficial, good for',e:'多聊天有利于口语提高。',l:3},
  {w:'有效',p:'形',m:'effective',e:'每天朗读是有效的学习方法。',l:3},
  {w:'预报',p:'动、名',m:'forecast; prediction',e:'天气预报说今天晴天。',l:3},
  {w:'预防',p:'动',m:'prevent',e:'多穿衣服，预防感冒。',l:3},
  {w:'预计',p:'动',m:'expect, estimate',e:'预计下周完成全部复习。',l:3},
  {w:'预习',p:'动',m:'preview',e:'课前预习新课文生词。',l:3},
  {w:'员',p:'后缀',m:'-er, staff',e:'服务员、学员都带“员”。',l:3},
  {w:'员工',p:'名',m:'staff, worker',e:'饭店员工服务很热情。',l:3},
  {w:'愿望',p:'名',m:'wish, desire',e:'我的愿望是说汉语很流利。',l:3},
  {w:'约',p:'动',m:'arrange, make an appointment',e:'约同学一起去图书馆。',l:3},
  {w:'乐队',p:'名',m:'band',e:'乐队现场演奏中文歌。',l:3},
  {w:'运输',p:'动',m:'transport, carry',e:'汽车运输生活用品。',l:3},
  {w:'杂志',p:'名',m:'magazine',e:'中文杂志内容很有趣。',l:3},
  {w:'早已',p:'副',m:'long ago, already',e:'他早已掌握了基础汉字。',l:3},
  {w:'造',p:'动',m:'make, build',e:'造新的教学楼。',l:3},
  {w:'造成',p:'动',m:'cause, result in',e:'地震造成了严重灾难。',l:3},
  {w:'责任',p:'名',m:'duty, responsibility',e:'每个人都有自己的责任。',l:3},
  {w:'增加',p:'动',m:'increase',e:'我的体重增加了不少。',l:3},
  {w:'增长',p:'动',m:'grow, increase',e:'中国的经济增长速度很快。',l:3},
  {w:'展开',p:'动',m:'unfold, carry out',e:'同学们展开了激烈的讨论。',l:3},
  {w:'张',p:'量、动',m:'sheet; open',e:'一张纸。',l:3},
  {w:'照',p:'动、介',m:'look at; according to',e:'照我看，你下个学期应该继续上中文课。',l:3},
  {w:'者',p:'后缀',m:'-er, -ist',e:'志愿者、读者都用“者”。',l:3},
  {w:'真实',p:'形',m:'real, true',e:'这是真实的中国故事。',l:3},
  {w:'争',p:'动',m:'fight, strive',e:'争取更多开口练习的机会。',l:3},
  {w:'争取',p:'动',m:'try for, strive for',e:'争取拿到汉语比赛的奖项。',l:3},
  {w:'整',p:'形、动',m:'whole; arrange',e:'整本书全部复习一遍。',l:3},
  {w:'整个',p:'形',m:'whole, entire',e:'整个班级一起外出活动。',l:3},
  {w:'整理',p:'动',m:'organize, sort out',e:'整理汉语笔记和练习册。',l:3},
  {w:'整齐',p:'形',m:'tidy, neat',e:'书本摆放整齐。',l:3},
  {w:'整体',p:'名',m:'whole, entirety',e:'整体理解课文意思。',l:3},
  {w:'整天',p:'名',m:'whole day',e:'整天待在家里学习汉语。',l:3},
  {w:'整整',p:'副',m:'full, whole',e:'整整朗读了两个小时课文。',l:3},
  {w:'正',p:'形',m:'correct, positive',e:'用正确的方式发音。',l:3},
  {w:'正式',p:'形',m:'formal',e:'正式场合使用礼貌用语。',l:3},
  {w:'证',p:'名',m:'certificate, card',e:'身份证、学生证都是证。',l:3},
  {w:'证件',p:'名',m:'documents, papers',e:'出门带好各类证件。',l:3},
  {w:'证据',p:'名',m:'evidence, proof',e:'文章里有事实证据。',l:3},
  {w:'证明',p:'动、名',m:'prove; certificate',e:'证明自己的汉语水平。',l:3},
  {w:'支',p:'量',m:'stick, branch',e:'一支笔、一支歌。',l:3},
  {w:'支持',p:'动',m:'support, back up',e:'同学互相支持，一起学习。',l:3},
  {w:'支付',p:'动',m:'pay, pay for',e:'支付书店买书的钱。',l:3},
  {w:'只',p:'量',m:'only, single',e:'一只猫、一只杯子。',l:3},
  {w:'直',p:'形、动、副',m:'straight; direct; directly',e:'直走就能到教室。',l:3},
  {w:'直播',p:'动',m:'live broadcast',e:'直播中文课堂教学。',l:3},
  {w:'直到',p:'动',m:'until, up to',e:'直到晚上十点才写完作业。',l:3},
  {w:'值',p:'动',m:'be worth, on duty',e:'今天我值日打扫教室。',l:3},
  {w:'值得',p:'动',m:'be worth',e:'长城非常值得去。',l:3},
  {w:'职工',p:'名',m:'staff, worker',e:'学校职工在认真地工作。',l:3},
  {w:'职业',p:'名',m:'job, occupation',e:'教师是很好的职业。',l:3},
  {w:'只好',p:'副',m:'have to, have no choice',e:'下雨了只好打车回家。',l:3},
  {w:'只是',p:'副、连',m:'only, merely',e:'只是生词有点多，不难。',l:3},
  {w:'只有',p:'连',m:'only, only have',e:'只有坚持练习才能进步。',l:3},
  {w:'指',p:'动',m:'point, refer to',e:'指着黑板上的汉字朗读。',l:3},
  {w:'指出',p:'动',m:'point out',e:'老师指出我的语法错误。',l:3},
  {w:'指导',p:'动',m:'guide, instruct',e:'老师指导我们写短文。',l:3},
  {w:'至今',p:'副',m:'so far, up to now',e:'至今我每天坚持听汉语。',l:3},
  {w:'至少',p:'副',m:'at least',e:'每天至少背二十个生词。',l:3},
  {w:'志愿',p:'名',m:'wish, volunteer',e:'志愿参加汉语交流活动。',l:3},
  {w:'志愿者',p:'名',m:'volunteer',e:'志愿者帮助留学生适应生活。',l:3},
  {w:'制定',p:'动',m:'make, formulate',e:'制定每日汉语学习计划。',l:3},
  {w:'制度',p:'名',m:'rule, system',e:'学校有完整的学习制度。',l:3},
  {w:'制造',p:'动',m:'make, produce',e:'工厂制造文具用品。',l:3},
  {w:'制作',p:'动',m:'make, produce',e:'制作简单中文手工卡片。',l:3},
  {w:'中部',p:'名',m:'middle part',e:'国家中部气候温和。',l:3},
  {w:'中华民族',p:'专有名词',m:'the Chinese nation',e:'中华民族历史悠久。',l:3},
  {w:'终于',p:'副',m:'finally, at last',e:'终于通过了HSK三级考试。',l:3},
  {w:'钟',p:'名',m:'clock, bell',e:'墙上的钟显示上课时间。',l:3},
  {w:'种',p:'量',m:'kind, type',e:'一种水果、一种方法。',l:3},
  {w:'种子',p:'名',m:'seed',e:'土里种下种子会长出植物。',l:3},
  {w:'重大',p:'形',m:'important, great',e:'自从认识了他，我的生活发生了重大变化。',l:3},
  {w:'周围',p:'名',m:'around, surrounding',e:'房子周围种满了花草。',l:3},
  {w:'猪',p:'名',m:'pig',e:'农场里饲养小猪。',l:3},
  {w:'主持',p:'动',m:'host, preside over',e:'老师主持汉语演讲比赛。',l:3},
  {w:'主动',p:'形',m:'active',e:'主动和中国人聊天练口语。',l:3},
  {w:'主任',p:'名',m:'director, head',e:'办公室主任管理日常工作。',l:3},
  {w:'主意',p:'名',m:'idea, plan',e:'我有一个能学好汉语的好主意。',l:3},
  {w:'主张',p:'动、名',m:'advocate; opinion',e:'他主张每天多开口练习。',l:3},
  {w:'注意',p:'动',m:'pay attention to',e:'注意汉字的正确书写。',l:3},
  {w:'祝',p:'动',m:'wish, congratulate',e:'祝你汉语越来越好。',l:3},
  {w:'抓',p:'动',m:'grasp, catch',e:'抓住学习汉语的好机会。',l:3},
  {w:'抓住',p:'动',m:'seize, grasp',e:'你抓住绳子。',l:3},
  {w:'专家',p:'名',m:'expert, specialist',e:'汉语专家讲解语法难点。',l:3},
  {w:'专门',p:'副',m:'special, specially',e:'我今天专门去买了那本书。',l:3},
  {w:'专题',p:'名',m:'special topic',e:'今天学习文化专题的生词。',l:3},
  {w:'专业',p:'名',m:'major, specialty',e:'我的专业是国际中文教育。',l:3},
  {w:'转',p:'动',m:'turn, change',e:'转去汉语三班学习。',l:3},
  {w:'转变',p:'动',m:'change, transform',e:'转变学习方法，提升效率。',l:3},
  {w:'状况',p:'名',m:'condition, situation',e:'说说你最近的学习状况。',l:3},
  {w:'状态',p:'名',m:'state, status',e:'保持良好的学习状态。',l:3},
  {w:'追',p:'动',m:'chase, pursue',e:'追求流利的汉语口语。',l:3},
  {w:'准',p:'形、副',m:'accurate; ready',e:'发音读准很重要。',l:3},
  {w:'资格',p:'名',m:'qualification, qualification',e:'这位运动员被取消了比赛的资格。',l:3},
  {w:'资金',p:'名',m:'fund, money',e:'学校有资金购买中文图书。',l:3},
  {w:'子女',p:'名',m:'children, sons and daughters',e:'父母关心子女学习。',l:3},
  {w:'自从',p:'介',m:'since',e:'自从来到中国，我爱上了汉语。',l:3},
  {w:'自动',p:'形、副',m:'automatic; automatically',e:'自动播放中文听力音频。',l:3},
  {w:'自觉',p:'形',m:'conscious, self-aware',e:'自觉完成每日学习任务。',l:3},
  {w:'自然',p:'名、形、副',m:'nature; natural; naturally',e:'你只要努力，自然会获得好成绩。',l:3},
  {w:'自身',p:'名',m:'oneself, self',e:'从自身找不足。',l:3},
  {w:'自主',p:'动',m:'independent, self-initiated',e:'自主安排汉语复习时间。',l:3},
  {w:'总',p:'副',m:'always, all',e:'我总喜欢朗读中文课文。',l:3},
  {w:'总结',p:'动、名',m:'summarize; summary',e:'每天总结当天学到的生词。',l:3},
  {w:'总是',p:'副',m:'always, all the time',e:'他总是最早来教室学习。',l:3},
  {w:'足够',p:'形',m:'enough',e:'我每天有足够的时间练习汉语。',l:3},
  {w:'足球',p:'名',m:'football, soccer',e:'周末和同学踢足球。',l:3},
  {w:'组合',p:'动',m:'combine, combine together',e:'组合词语造完整句子。',l:3},
  {w:'左右',p:'名、动',m:'left and right; around',e:'我在上海生活了三年左右。',l:3},
  {w:'作品',p:'名',m:'work, writing',e:'这篇短文是我的中文作品。',l:3},
  {w:'作者',p:'名',m:'author, writer',e:'这篇课文的作者是汉语老师。',l:3},
  {w:'做客',p:'动',m:'visit someone\'s home',e:'周末去中国朋友家做客。',l:3},
  {w:'状态',p:'名',m:'state, condition',e:'保持放松的学习状态。',l:3},
];
